MySite/MySite/urls.py
from django.contrib import admin
from cats.views import page_not_found

handler404 = page_not_found

from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cats.urls')),
    path('users/', include('users.urls',
                           namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MySite/cats/urls.py
from django.urls import path, register_converter
from cats import views, converters
from django.contrib import admin

from cats.views import CatsCategory

register_converter(converters.FourDigitYearConverter,"year4")
urlpatterns = [
    path('', views.CatsHome.as_view(),name='home'),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(),
         name='post'),
    path('category/<slug:cat_slug>/', CatsCategory.as_view(),
         name='category'),
    path('tag/<slug:tag_slug>/', views.show_tag_postlist,
         name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(),
         name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(),
         name='delete_page'),

]

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Котофейник"

MySite/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(),
         name='login'),
    path('logout/', LogoutView.as_view(),
         name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(),
         name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path('register/', views.RegisterUser.as_view(),
         name='register'),
    path('profile/', views.ProfileUser.as_view(),
         name='profile'),
    path(
        'password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'
    ),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
]

MySite/users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm

User = get_user_model()



class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        model = get_user_model()

    fields = ['username', 'password']

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    password2 = forms.CharField(
        label='Повтор пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        disabled=True,
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )

    email = forms.CharField(
        disabled=True,
        label='E-mail',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )

    this_year = datetime.today().year
    date_birth = forms.DateField(
        label='Дата рождения',
        widget=forms.SelectDateWidget(
            years=tuple(range(this_year - 100, this_year - 5))
        )
    )

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

MySite/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <!-- Ошибки, не привязанные к конкретному полю -->
    <div class="form-error">
        {{ form.non_field_errors }}
    </div>

    <!-- Вывод полей формы с подписями и ошибками -->
    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Войти</button></p>
    <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
</form>
{% endblock %}

MySite/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<h1>Пароль успешно изменен!</h1>
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

MySite/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">
        {{ form.non_field_errors }}
    </div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Изменить пароль</button>
    </p>
</form>
{% endblock %}

MySite/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>
    Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
    <a href="{% url 'users:login' %}">входа в систему</a>.
</p>
{% endblock %}

MySite/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">
        {{ form.non_field_errors }}
    </div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">
            {{ f.errors }}
        </div>
    {% endfor %}

    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
{% endblock %}

MySite/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>
    {% translate "We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}
</p>
<p>
    {% translate "If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder." %}
</p>
{% endblock %}

MySite/users/templates/users/password_reset_email.html
{% load i18n %}

{% blocktrans %}Вы получили это письмо, потому что был сделан запрос на сброс пароля для вашей учётной записи на сайте {{ site_name }}.{% endblocktrans %}

{% blocktrans %}Пожалуйста, перейдите по следующей ссылке и выберите новый пароль:{% endblocktrans %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% blocktrans %}Ваш логин, если вы его забыли: {{ user.get_username }}{% endblocktrans %}

{% trans "Спасибо за использование нашего сайта!" %}

{% blocktrans %}Команда {{ site_name }}{% endblocktrans %}

MySite/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Сбросить по E-mail</button>
    </p>
</form>
{% endblock %}

MySite/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Профиль</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if user.photo %}
        <p><img src="{{ user.photo.url }}" alt="Фото пользователя"></p>
    {% else %}
        <p ><img src="{{ default_image }}" alt="Фото по умолчанию" width="200" height="200"></p>
    {% endif %}

    <div class="form-error">
        {{ form.non_field_errors }}
    </div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Сохранить</button>
    </p>
    <hr>
    <p ><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
</form>
{% endblock %}

MySite/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />

    <!-- Ошибки, не привязанные к конкретным полям -->
    <div class="form-error">{{ form.non_field_errors }}</div>

    <!-- Поля формы -->
    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <!-- Кнопка отправки -->
    <p>
        <button type="submit">Регистрация</button>
    </p>
</form>
{% endblock %}

MySite/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать!</h1>

<p>
    Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по
    этой <a href="{% url 'users:login' %}">ссылке</a>.
</p>
{% endblock %}